### ISSUE TITLE
求助：验证码校验成功，登录失败

### ISSUE THREAD

**Issue by liangzhdp** [470390366/buy_12306#1]
验证码校验成功
正在登陆.....
Traceback (most recent call last):
  File "run.py", line 314, in <module>
    onetwothreezoresix.login()
  File "run.py", line 108, in login
    login_req_result = json.loads(login_req)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by 470390366** [comment]
cookie失效了,你自己抓包   把login里面下面三个改成你抓的就了， 请求一下12306 就返回你这个cookie。
self.session.cookies['RAIL_DEVICEID'] = 'XQ0xiH-VnSGYwebVyByxBEU1yJqsStE6f1Khg9ZD6tMgYBV-vaqYc4QDHqaHtiv0WjiiD2VmmElfDOLIzrAXSTpmx_ggRwmtCDd3az9erjsnV2k2Y73l63q_zyVoIPBbQG_4gTnAoK8fQVKgkExML_wg04ayGxQ'
self.session.cookies['RAIL_EXPIRATION'] = '1565922992430'
self.session.cookies['route'] = 'c5c62a339e7744272a54643b3be5bf64'

**Comment by ii2day** [comment]
> 验证码校验成功
> 正在登陆.....
> Traceback (most recent call last):
> File "run.py", line 314, in 
> onetwothreezoresix.login()
> File "run.py", line 108, in login
> login_req_result = json.loads(login_req)
> File "/usr/lib/python3.7/json/**init**.py", line 348, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

cookie失效了,你自己抓包 把login里面下面三个改成你抓的就了， 请求一下12306 就返回你这个cookie。最近有点忙  忙完我改成自动版本的。
self.session.cookies['RAIL_DEVICEID'] = 'XQ0xiH-VnSGYwebVyByxBEU1yJqsStE6f1Khg9ZD6tMgYBV-vaqYc4QDHqaHtiv0WjiiD2VmmElfDOLIzrAXSTpmx_ggRwmtCDd3az9erjsnV2k2Y73l63q_zyVoIPBbQG_4gTnAoK8fQVKgkExML_wg04ayGxQ'
self.session.cookies['RAIL_EXPIRATION'] = '1565922992430'
self.session.cookies['route'] = 'c5c62a339e7744272a54643b3be5bf64'

**Comment by liangzhdp** [comment]
多谢。不过改了上面三项还是不行呀。
我在chromium获取的cookie

**Comment by ii2day** [comment]
> 多谢。不过改了上面三项还是不行呀。
> 我在chromium获取的cookie

session.cookies['RAIL_DEVICEID'] = 'YAE3tFrNlYhEj74DUpKQowt_8bNWYcirxto6Cn-4TY4MJ_Xguc4iY2T4MeP2eA9vwRq8Dg62r4Jlm9I9qAcLhgcyWDKhOQNPVVE_5ISJiBuwdsZt2a3Bschq_opSRKxp6rCe2UVGvFYGK3KtpO1AbX8DHAmxtJdq'
session.cookies['RAIL_EXPIRATION'] = '1567592385602'
session.cookies['route'] = '6f50b51faa11b987e576cdb301e545c4'

这是我刚抓的  你改成这个就可以了，我用的火狐   chrome 有时候抓不到没有返回值

**Comment by liangzhdp** [comment]
哦，难道是我机器问题？改了你刚发布的还是不行：

self.session.cookies['RAIL_DEVICEID'] = 'YAE3tFrNlYhEj74DUpKQowt_8bNWYcirxto6Cn-4TY4MJ_Xguc4iY2T4MeP2eA9vwRq8Dg62r4Jlm9I9qAcLhgcyWDKhOQNPVVE_5ISJiBuwdsZt2a3Bschq_opSRKxp6rCe2UVGvFYGK
3KtpO1AbX8DHAmxtJdq'
self.session.cookies['RAIL_EXPIRATION'] = '1567592385602'
self.session.cookies['route'] = '6f50b51faa11b987e576cdb301e545c4'


输入验证码索引(见上图，以','分割）：2,4
验证码校验成功
正在登陆.....
登录成功
验证通过
Traceback (most recent call last):
  File "run.py", line 327, in <module>
    onetwothreezoresix.cheak_ticket(user_info)
  File "run.py", line 146, in cheak_ticket
    cheak_req_json = json.loads(cheak_req)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ii2day** [comment]
> 哦，难道是我机器问题？改了你刚发布的还是不行：
> 
> ```
>     self.session.cookies['RAIL_DEVICEID'] = 'YAE3tFrNlYhEj74DUpKQowt_8bNWYcirxto6Cn-4TY4MJ_Xguc4iY2T4MeP2eA9vwRq8Dg62r4Jlm9I9qAcLhgcyWDKhOQNPVVE_5ISJiBuwdsZt2a3Bschq_opSRKxp6rCe2UVGvFYGK
> ```
> 
> 3KtpO1AbX8DHAmxtJdq'
> self.session.cookies['RAIL_EXPIRATION'] = '1567592385602'
> self.session.cookies['route'] = '6f50b51faa11b987e576cdb301e545c4'
> 
> 输入验证码索引(见上图，以','分割）：2,4
> 验证码校验成功
> 正在登陆.....
> 登录成功
> 验证通过
> Traceback (most recent call last):
> File "run.py", line 327, in 
> onetwothreezoresix.cheak_ticket(user_info)
> File "run.py", line 146, in cheak_ticket
> cheak_req_json = json.loads(cheak_req)
> File "/usr/lib/python3.7/json/**init**.py", line 348, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

额  这个 登录成功了   ，没问题  好想是下面出问题了  估计 12306又更改反爬了。

**Comment by ii2day** [comment]
> 哦，难道是我机器问题？改了你刚发布的还是不行：
> 
> self.session.cookies['RAIL_DEVICEID'] = 'YAE3tFrNlYhEj74DUpKQowt_8bNWYcirxto6Cn-4TY4MJ_Xguc4iY2T4MeP2eA9vwRq8Dg62r4Jlm9I9qAcLhgcyWDKhOQNPVVE_5ISJiBuwdsZt2a3Bschq_opSRKxp6rCe2UVGvFYGK
> 3KtpO1AbX8DHAmxtJdq'
> self.session.cookies['RAIL_EXPIRATION'] = '1567592385602'
> self.session.cookies['route'] = '6f50b51faa11b987e576cdb301e545c4'
> 
> 输入验证码索引(见上图，以','分割）：2,4
> 验证码校验成功
> 正在登陆.....
> 登录成功
> 验证通过
> Traceback (most recent call last):
> File "run.py", line 327, in 
> onetwothreezoresix.cheak_ticket(user_info)
> File "run.py", line 146, in cheak_ticket
> cheak_req_json = json.loads(cheak_req)
> File "/usr/lib/python3.7/json/**init**.py", line 348, in loads
> return _default_decoder.decode(s)
> File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
> obj, end = self.raw_decode(s, idx=_w(s, 0).end())
> File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

我明天找时间把程序更新下。

**Comment by liangzhdp** [comment]
太好了，谢谢。

**Comment by ii2day** [comment]
> 太好了，谢谢。

已经修改完毕 可以使用了

**Comment by liangzhdp** [comment]
是不是因为座位类型太少（商务座(9),一等座(M),二等座(O[英文大写字母O]),一等卧(I),二等卧(J)），导致无法买K字头的车呀？

开始查询 K9139 票数
Traceback (most recent call last):
  File "run.py", line 335, in <module>
    onetwothreezoresix.cheak_ticket(user_info)
  File "run.py", line 159, in cheak_ticket
    self.__statistics_tickets(tmplist)
  File "run.py", line 183, in __statistics_tickets
    self.key_check_isChange =re.findall(r"'key_check_isChange':'(.*?)'",req3)[0]
IndexError: list index out of range

**Comment by ii2day** [comment]
> ck_isChange =re.findall(r"'key_check_isChange':'(.*?)'",req3)[0]
> IndexError: list index out of range

我只写了  高铁跟动车的 购票  k字头的没写， 有时间我会把 k字头加上

**Comment by liangzhdp** [comment]
会不会还是有个配置文件的比较方便一点？省得每次都填一堆资料。

**Comment by ii2day** [comment]
> 会不会还是有个配置文件的比较方便一点？省得每次都填一堆资料。

嗯嗯   之后会添加上的
